import type { ResearchRun } from "./schemas"

const hashA = "a".repeat(64)
const hashB = "b".repeat(64)
const hashC = "c".repeat(64)

export const showcaseRun: ResearchRun = {
  run_id: "run-demo-quality-001",
  status: "blocked",
  scope: {
    scope_id: "scope-v1",
    objective: "定位 LINE-A 产品 P-100 在 2026-07-15 起质量不良率上升的可证伪原因",
    asset_ids: ["LINE-A", "BATCH-DEMO-0715"],
    data_domains: ["quality", "operations", "documents"],
  },
  plan_version: "plan-v1",
  scope_version: "scope-v1",
  todos: [
    {
      todo_id: "todo-1",
      title: "确认异常起点与影响范围",
      question: "不良率何时显著偏离稳定基线？",
      data_scope: "LINE-A / P-100 / 2026-07-01 至 2026-07-21",
      required_tools: ["quality.onset", "quality.control_chart"],
      status: "completed",
      outcome: "evidence",
      dependencies: [],
      evidence_ids: ["ev-quality-onset"],
      negative_results: [],
      source_quality: "内部质量检验记录，完整性通过",
      candidate_conclusion: "异常于 2026-07-15 出现，受影响窗口不良率为 1.35%",
      confidence: 0.94,
      falsification_conditions: ["补录数据将异常起点前移超过一个班次"],
      cost_units: 1,
      failure_reason: null,
    },
    {
      todo_id: "todo-2",
      title: "核对过程参数漂移",
      question: "异常窗口内关键温度是否发生可重复漂移？",
      data_scope: "LINE-A 温度记录，异常前后各 7 天",
      required_tools: ["quality.drift", "operations.equipment"],
      status: "completed",
      outcome: "conflict",
      dependencies: ["todo-1"],
      evidence_ids: ["ev-temp-drift", "ev-maintenance"],
      negative_results: [],
      source_quality: "传感器数据高质量，维修记录存在版本冲突",
      candidate_conclusion: "温度均值漂移 5.95°C，与维修版本记录不一致",
      confidence: 0.71,
      falsification_conditions: ["校准记录证明温度变化来自传感器偏置"],
      cost_units: 2,
      failure_reason: null,
    },
    {
      todo_id: "todo-3",
      title: "验证批次与材料关联",
      question: "异常是否仅与特定来料批次共同出现？",
      data_scope: "LINE-A 批次谱系与脱敏来料记录",
      required_tools: ["operations.material"],
      status: "awaiting_human",
      outcome: null,
      dependencies: ["todo-1"],
      evidence_ids: [],
      negative_results: ["未发现其他产线可比批次"],
      source_quality: "跨域权限待批准",
      candidate_conclusion: null,
      confidence: null,
      falsification_conditions: ["其他产线同批次未出现异常"],
      cost_units: 1,
      failure_reason: "等待跨域访问 Gate",
    },
  ],
  evidence: [
    {
      evidence_id: "ev-quality-onset",
      source_uri: "workspace://quality/inspection_results.csv",
      source_version: "quality-v1",
      retrieved_at: "2026-07-22T08:00:00+00:00",
      permission_level: "tenant:demo/line:a/read",
      source_quality: "完整，字段校验通过",
      tool_call_id: "tool-call-001",
      query: "比较基线与异常窗口不良率",
      partition: "internal_factory_fact",
      status: "found",
      negative_result: false,
      content_hash: hashA,
      confidence: 0.94,
      data_window: "2026-07-01/2026-07-21",
    },
    {
      evidence_id: "ev-temp-drift",
      source_uri: "workspace://operations/process_temperature.csv",
      source_version: "operations-v2",
      retrieved_at: "2026-07-22T08:02:00+00:00",
      permission_level: "tenant:demo/line:a/read",
      source_quality: "采样连续，校准待核验",
      tool_call_id: "tool-call-002",
      query: "检测异常窗口温度均值漂移",
      partition: "internal_factory_fact",
      status: "found",
      negative_result: false,
      content_hash: hashB,
      confidence: 0.82,
      data_window: "2026-07-08/2026-07-21",
    },
    {
      evidence_id: "ev-maintenance",
      source_uri: "workspace://documents/maintenance_notice.md",
      source_version: "doc-v2",
      retrieved_at: "2026-07-22T08:03:00+00:00",
      permission_level: "tenant:demo/documents/read",
      source_quality: "两个版本陈述冲突",
      tool_call_id: "tool-call-003",
      query: "核对维修时点与参数调整",
      partition: "external_general_knowledge",
      status: "conflict",
      negative_result: false,
      content_hash: hashC,
      confidence: 0.56,
      data_window: "2026-07-14/2026-07-16",
    },
  ],
  notes: [
    {
      note_id: "note-1",
      note_type: "fact",
      status: "approved",
      todo_id: "todo-1",
      body: "异常窗口不良率 1.35%，是基线 0.17% 的 8.1 倍。",
      input_hash: hashA,
      evidence_ids: ["ev-quality-onset"],
      reviewer: "QA Reviewer",
      supporting_evidence_ids: [],
      counter_evidence_ids: [],
      missing_evidence_ids: [],
      next_action: null,
    },
    {
      note_id: "note-2",
      note_type: "hypothesis",
      status: "draft",
      todo_id: "todo-2",
      body: "温度漂移可能提高缺陷风险，但维修记录冲突，当前不能作为根因结论。",
      input_hash: hashB,
      evidence_ids: [],
      reviewer: null,
      supporting_evidence_ids: ["ev-temp-drift"],
      counter_evidence_ids: ["ev-maintenance"],
      missing_evidence_ids: [],
      next_action: "由工艺负责人核验校准与维修原始记录",
    },
  ],
  budget: {
    max_tool_calls: 12,
    max_cost: 20,
    max_rows_scanned: 20_000,
    max_elapsed_ms: 120_000,
    consumed_tool_calls: 4,
    consumed_cost: 4.5,
    consumed_rows_scanned: 6_240,
    consumed_elapsed_ms: 18_420,
  },
  gates: [
    { gate_id: "gate-plan", name: "research_plan", input_hash: hashA, plan_version: "plan-v1", scope_version: "scope-v1", status: "approved", rationale: "范围与预算已确认" },
    { gate_id: "gate-cross", name: "cross_domain_access", input_hash: hashB, plan_version: "plan-v1", scope_version: "scope-v1", status: "awaiting_human", rationale: "读取脱敏来料谱系" },
    { gate_id: "gate-budget", name: "budget_extension", input_hash: hashA, plan_version: "plan-v1", scope_version: "scope-v1", status: "pending", rationale: null },
    { gate_id: "gate-validation", name: "validation_experiment", input_hash: hashB, plan_version: "plan-v1", scope_version: "scope-v1", status: "pending", rationale: null },
    { gate_id: "gate-final", name: "final_conclusion", input_hash: hashC, plan_version: "plan-v1", scope_version: "scope-v1", status: "pending", rationale: null },
  ],
  paused: false,
  current_tool: null,
  blocked_reason: "维修记录存在版本冲突，且跨域访问待批准",
  report_markdown: "## 1. 研究问题与范围\n质量异常自 2026-07-15 出现。\n\n## 2. 数据与方法\n仅使用脱敏、只读样例。\n\n## 3. 已确认事实\n异常窗口不良率为 1.35%。\n\n## 4. 候选解释\n温度漂移为候选因素。\n\n## 5. 反证与未知\n维修记录存在冲突。\n\n## 6. 验证计划\n核验校准与维修原始记录。\n\n## 7. 结论与边界\n仅供教学和人工决策支持。",
}
